### ISSUE TITLE
internal USB 2.0 ports 

### ISSUE THREAD

**Issue by voelie** [yilmazca/intel-i9-10900K-Asus-prime-z490-a-hackintosh#6]
Unable to activate internal USB 2.0 ports , not even with usbinjectall ?

**Comment by cjazinski** [comment]
I have the same board but running on the i7. I was able to get the USBPorts mapped. I had problem with the InjectAll but after reading and re-reading I was able to build my USBPorts.kext. Internal USB is working as its powering the BT/Wifi card (Fenvi) until the ports where mapped correctly I was unable to use it. 

[USBPorts.kext.zip](https://github.com/yilmazca/intel-i9-10900K-Asus-prime-Z490A-hackintosh/files/5175745/USBPorts.kext.zip)

**Comment by voelie** [comment]
Hi ,

What did you have to do exactely to get your usb ports mapped ? I can’t manage to do so using the normal way,
This usbkext is not working for me , i have even less porte with it , maybe because i updated the bios to the latest version

Kind regards,

Pascal

Verstuurd vanaf mijn iPad

**Comment by cjazinski** [comment]
You would need to also modify your config to use the kext. I used the port mapping tool as he explained but my mapping looked different. This is what is shown my machine 

![Screen Shot 2020-09-04 at 11 27 22 AM](https://user-images.githubusercontent.com/2166202/92263094-b27e7a00-eea1-11ea-9037-6db03ca54c34.png)

**Comment by voelie** [comment]
Hi ,

I understand what you mean ,
But what is the reason i cannot use my internal usb ports when using usbinjectall.kext ?
If i van’t see them i cannot map them as well
I have done this succesfully on other systems but for this board it seems to be an issue

Kind regards,

Pascal

Verstuurd vanaf mijn iPad

**Comment by ozbenwoo** [comment]
I have same problem with internal USB ports mapping. I have same motherboard with i7 10700 cpu. everything works except internal USB ports, so my fenvi card bluetooth does not work because no power supply. I check the internal ports in Windows 10, the internal ports seem to under another USB hub. the hackintool can not show these internal ports. I am not too concerned with those internal USB ports, they are USB2 ports, bluetooth does not bother me.

**Comment by voelie** [comment]
There should be a way to fix this but how ... :)

**Comment by voelie** [comment]
> You would need to also modify your config to use the kext. I used the port mapping tool as he explained but my mapping looked different. This is what is shown my machine
> 
> ![Screen Shot 2020-09-04 at 11 27 22 AM](https://user-images.githubusercontent.com/2166202/92263094-b27e7a00-eea1-11ea-9037-6db03ca54c34.png)

I see that you have USR 1 & 2 in your usb list , i have never seen that , are those the internal usb ports ?

**Comment by voelie** [comment]
No matter what I try I cannot see the internal USB ports and I also tried USBInjectAll_v0.7.5_z490-p.kext but with that kext my hack won't even boot

Update : it boots with clover , i can now see more usb ports but still not the internals

**Comment by voelie** [comment]
okey I figured it out , all is working now
[usbports.zip](https://github.com/yilmazca/intel-i9-10900K-Asus-prime-Z490A-hackintosh/files/5184778/usbports.zip)
